name: Deploy to AWS

on:
  workflow_dispatch: # Allows manual trigger
  repository_dispatch: # Triggered by JIRA webhook
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          aws s3 cp index.html s3://myjiraapphimanshu/
